### ISSUE TITLE
[BUG] On Windows the App seem to Run in the Background after closing

### ISSUE THREAD

**Issue by ysfscream** [emqx/MQTTX#1020]
On Windows, the App seems to Run in the Background after closing, without a tray icon. I don't like that.

_Originally posted by @hofq in https://github.com/emqx/MQTTX/issues/771#issuecomment-1199216965_

**Comment by ysfscream** [comment]
Hi @ni00, could you please help us check if the issue with MQTTX running in the background on Windows after closing is still present? If it's fixed, we might close the issue. Thanks for your help, and I'm sorry to take your time here.

**Comment by ni00** [comment]
@ysfscream Okay, I will test this issue on both Win10 and Win11 this week.

**Comment by ni00** [comment]
I tested MQTTX v1.9.9 on both Win11 and Win10 and found that the MQTTX process in the task manager will automatically end after MQTTX is closed. At the same time, since this issue has not received relevant feedback for a long time, the issue may have been resolved. Therefore, we can consider closing it.

**Comment by hofq** [comment]
I cannot test it myself as i do not use windows anymore

**Comment by ysfscream** [comment]
Thanks all. I will close it.
