### ISSUE TITLE
[Feature] Regarding the certificate part, the concepts are mixed up

### ISSUE THREAD

**Issue by wuyoooo** [emqx/MQTTX#1168]
![image](https://user-images.githubusercontent.com/118347652/207826449-60a78d1c-e4b5-4f2d-9640-85362907b834.png)

关于证书部分，概念有点揉在一起了。

证书类型： CA服务商签名，和自签名。
但是选择自签名的时候 CA文件传的是服务端CA证书，却又有客户端证书文件输入框，有点难以理解，有点绕。
**建议：将服务端证书和客户端证书分开配置**
- 服务端证书 提供两个选项，1，服务商签名，2，自签名（必须输入自签名证书CA）
- 客户端证书 提供两个选项 1，单向认证，2，双向认证（必须输入 证书和私钥）

**Comment by ysfscream** [comment]
Yes, for the certificate here, we previously felt that there are some concepts are actually blurred; this is because of the early design reasons and your feedback for us to reorganize the ideas; we sincerely thank you, and we will follow up to see if we can better optimize, if there is progress, we will let you know, thanks again.
