### ISSUE TITLE
[Bug] Topic copy past bug 

### ISSUE THREAD

**Issue by Siqiu** [emqx/MQTTX#1306]
#### What did I do

Something you have done.
I connect to the broker, pastint  the topic string that include "EJ65mmcIl4IPlKJ4E" into the pyload topic (bottom right corner)

#### What happened

Get an error.
when I copy it back I got "EJ65mmcll4IPIKJ4E". It looks same but 8th and 13th letter are exchanged.

#### Expected

What is the expected result.
It should not change what I pasted.

#### Environment

- OS: OS version, e.g. macOS Monterey 12.4
- MQTTX version, e.g. v1.9.2

#### More detail
The most  important thing is that I copy that string from CLion 2022.3.2 or VScode  Version: 1.78.2
More detail include `log` information or screenshot

**Comment by ysfscream** [comment]
Thank you for bringing this to our attention. This issue is a character encoding or display problem, possibly caused by the software (CLion, VScode, or MQTTX) or a system-level issue.

To help us better diagnose the problem, please try copying and pasting the string from different applications to see if the issue persists. Also, could you provide the Binary, Hex, or Base64 string representation before and after the copy-paste operation?

This information will help us understand whether this issue is specific to MQTTX. If so, we'll do our best to locate and fix it. Please provide as much detail as possible, including reproduction steps and your environment information.

Thanks!

<img width="740" alt="image" src="https://github.com/emqx/MQTTX/assets/21299158/a69312b9-93c5-44a6-9d28-108f5a212b2a">

**Comment by Siqiu** [comment]
Here are the hex :
EJ65mmcIl4IPlKJ4E :
45 4A 36 35 6D 6D 63 49 6C 34 49 50 6C 4B 4A 34 45

EJ65mmcll4IPIKJ4E:
45 4A 36 35 6D 6D 63 6C 6C 34 49 50 49 4B 4A 34 45

I've update the latest version of MQTTX, I cannot reshow this.

The problem exit at that time. However it is disappear.
