### ISSUE TITLE
[Bug] Access Denied on download attempt (Mac)

### ISSUE THREAD

**Issue by kpko** [emqx/MQTTX#1315]
#### What did I do

Hi, I tried to download the mqttx cli for Mac. I clicked on the download link or tried to run the shell script on https://mqttx.app/cli in the "Mac" tab.

#### What happened

The following error occured:

```xml
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>5VMPB8C4DX8E74AR</RequestId>
  <HostId>N1n/rY7NY0lqt0YnrthfGgH5BM6W7uaEH7hmX//9+YaLXyHzKx6oDBGUd+ikW22Eba4QMtae4Y4=</HostId>
</Error>
```

#### Expected

A valid download for the mqttx cli.

#### Environment

- OS: OS version, e.g. macOS Ventura

**Comment by ysfscream** [comment]
@kpko I'm sorry for the inconvenience. Indeed, there was an issue with the file we uploaded previously. We have since corrected the problem. Now, you should be able to download the mqttx cli without issues.

We highly recommend you use Homebrew to install mqttx cli. Run the following command in your terminal:

```
brew install emqx/mqttx/mqttx-cli
```

Thanks for your feedback and use!

**Comment by ysfscream** [comment]
If this issue does not occur again, I will close it. Thanks for your feedback.
