### ISSUE TITLE
client cert and key shouldn't be mandatory

### ISSUE THREAD

**Issue by daadu** [emqx/MQTTX#133]
To connect to a broker that is configured with a self-signed server certificate, client cert and key are not mandatory. MQTTX is assuming that the SSL connection is mutual. The broker could be configured for only one-sided (client-side) SSL and use username and password based authentication instead of cert based authentication.

**Comment by ysfscream** [comment]
@daadu Hi, thanks for your feedback. I think you mean is that when TLS / SSL is enabled for authentication and broker is self-signed. It's a one-way authentication, so you only need to use CA certificate file?

**Comment by daadu** [comment]
@ysfscream yes you got my point.

**Comment by ysfscream** [comment]
@daadu OK, I think your are correct, there is no problem with this configuration. Two-way authentication can only be accessed by clients allowed by the server, the security is relatively high.

Actually, it should be my problem, because I'm using `mqtt.js` and have not verified that one-way authentication only requires a client CA certificate file, will it work? So I first mandated the use of two-way authentication, but I'm fixing this and thanks for your reminder.

I will fix it in the next version and tell you here if it's fixed. Thanks again :)

**Comment by daadu** [comment]
You can refer to this document: http://www.steves-internet-guide.com/mosquitto-tls/ for configuring SSL on mosquito broker.

It specifies:

> **Client Requirements**
> - A CA (certificate authority) certificate of the CA that has signed the server certificate on the Mosquitto Broker.
> 
> **Broker Requirements**
> - CA certificate of the CA that has signed the server certificate on the Mosquitto Broker.
> - CA certificated server certificate.
> - Server Private key for decryption.

**Comment by ysfscream** [comment]
@daadu Thank you for sharing the document, it helps lot.

I tried to fix this issue in #141 , hope it fixed. You can download the latest version to test and report the bug here. If you can also submit PRs to make it better and more perfect! :)

**Comment by daadu** [comment]
@ysfscream Sure, I will try my best to contribute.
