### ISSUE TITLE
[Bug] mqttx 1.9.1 cannot be uninstalled - win 10

### ISSUE THREAD

**Issue by ves011** [emqx/MQTTX#1358]
#### What did I do

Try to install new version 1.9.4. It fails with the message mqttx is running -> cannot stop
try to uninstall using Uninstall MQTTX.exe, it fails with the same message

#### Environment

- OS: windows 10 21H2 / build 19044.3086
- MQTTX version, 1.9.1

**Comment by ni00** [comment]
Hello @ves011 ,

Regarding the issue you reported, I have performed tests on both Win10 (21H2) and Win11, and I could not reproduce it. I was able to stop or close MQTTX for both automatic and manual updates successfully. I am speculating whether it could be associated with your system administrator permissions or the permissions of the installation directory?

I will keep this issue open. If you have any additional information, or if other users comment on this issue, I will run the tests again. If I am able to reproduce the issue at that time, I will proceed to address it further.

Thank you once again.

**Comment by ysfscream** [comment]
Thanks for your feedback!

Welcome to try the new MQTTX release at https://github.com/emqx/MQTTX/releases/tag/v1.9.5. If problems persist, please let us know, and we will quickly address them.

**Comment by kerryland** [comment]
fwiw I have the same problem with 1.9.3 trying to automatically upgrade to 1.9.5. Process Manager shows the mqttx.exe being killed, and MQTTX-Setup-1.9.5.exe executing, but no progress is made.

Because I couldn't uninstall 1.9.3 gracefully I just deleted the entire contents of the "Program Files\MQTTX" folder and ran MQTTX-Setup-1.9.5.exe again. Everything works fine now.

This is not a bug report, just some advice for the next random person who arrives here via a search :-)

**Comment by FiveElementNinja** [comment]
I'm also having this problem in Windows 10. I'm stuck on 1.9.0. I've tried uninstalling from Add/Remove programs, using the update prompt from within the app, and trying to install the latest version from the download from the website. In all instances the install or uninstall fails because it says the app is running, even though it's not.
