### ISSUE TITLE
The start-up loading page turns blank immediately, previous issue not resolved

### ISSUE THREAD

**Issue by AdonLuo** [emqx/MQTTX#1406]
https://github.com/emqx/MQTTX/issues/1370#issue-1812987608
已经升级到1.9.5 了，也使用了挺长一段时间，但是昨天突然又出现加载后空白的情况，而且卸载重装了也不行

---

I've already upgraded to 1.9.5 and have been using it for quite some time. However, yesterday it suddenly started showing a blank page after loading, and even uninstalling and reinstalling didn't help.

**Comment by ysfscream** [comment]
@AdonLuo, I'm genuinely sorry for the inconvenience you're facing.

Based on your description, the issue might be caused by accumulating a significant amount of historical data over time. Please confirm if a substantial amount of data was received that wasn't cleared before the blank screen issue occurred.

If you're on a Windows system, you might try navigating to `%USERPROFILE%\AppData\Roaming\MQTTX` and deleting the `MQTTX.db` file. After doing so, please restart the application to see if the issue is resolved.

This issue appears on Windows frequently. Regrettably, we have not yet been able to pinpoint the exact cause. We are very sorry for the inconvenience, and rest assured we are actively investigating and will strive to address this problem promptly.

Thank you for your understanding and support!

**Comment by AdonLuo** [comment]
感谢，确实可以启动了，之前就算是卸载，再次安装也不起作用，我想应该是这个用户文件没删除导致，只是之前的连接信息都没了，不过这不重要

**Comment by AdonLuo** [comment]
@ysfscream 
谢谢，确实可以启动了，之前就算是卸载再次，安装也无效，我想应该是这个用户文件没删除导致的，只是之前的连接信息都没有了，不过这不重要

**Comment by AdonLuo** [comment]
还是有问题，接收处理不过来或者不知道什么情况的时候，就是无法正常使用了 @ysfscream

**Comment by ysfscream** [comment]
- Use two ways to handle the white screen situation at https://github.com/emqx/MQTTX/releases/tag/v1.10.0
    - By resetting the database
    - Optimizing the display of large messages in the message list

Thanks for your feedback. If there is any problem, I will reopen this issue.
