### ISSUE TITLE
Can't connect to broker.emqx.io with host mqtt:// and port 1883 || MQTT.js onError trigger, Error: connect ECONNREFUSED 54.244.173.190:1883

### ISSUE THREAD

**Issue by Thinhle2701** [emqx/MQTTX#1503]
**What did I do?**
connect to broker.emqx.io with host mqtt:// and port 1883

**What happened?**
 I cant connect to broker.emqx.io with host mqtt:// and port 1883 in MQTTX application on windows
"connect fail, MQTT.js onError trigger, Error: connect ECONNREFUSED 54.244.173.190:1883" at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)

**Expected**
Solve this problem

**Description**

I have used MQTTX for 3 months. It was really good to apply mqtt to my project IOT. However, I have problem with MQTTX. I cant connect to broker.emqx.io with host mqtt:// and port 1883 in MQTTX application on windows

When I see log, I saw that It can not connect to broker.emqx.io because "connect fail, MQTT.js onError trigger, Error: connect ECONNREFUSED 54.244.173.190:1883" at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)

I think it maybe from broker.emqx.io server with Port 1883 because I still use websocket to connect broker.emqx.io with Port 8083

Please help me solve this problem

![image](https://github.com/emqx/MQTTX/assets/59316091/1656806a-38b0-4351-9ad7-267af20453ca)

**Comment by ysfscream** [comment]
Hi @Thinhle2701 

First and foremost, I apologize for being unable to respond to your issue immediately. I appreciate your patience.

About the problem you had while trying to connect to the EMQX broker (broker.emqx.io) using MQTTX, I have done some tests and connected to the broker server. This indicates that the server is active and accepting connections on port 1883.

Given that you are experiencing the "connect ECONNREFUSED" error, this usually points to a network connectivity issue. Possible causes include network firewalls or security settings blocking access to port 1883, or there could be some restrictions within your network environment.

I suggest the following steps to troubleshoot:

1. **Check Your Network Connection**: Ensure that your network is stable and that no firewall or security software prevents you from accessing external servers.

2. **Try a Different Network Environment**: If possible, try connecting to the broker server from another network to determine if the issue is related to specific network settings.

3. **Verify Client Configuration**: Double-check the MQTTX client configuration settings to ensure the broker address and port are correctly set.

4. **Install EMQX Locally for Testing**: Consider installing EMQX locally using Docker to see if the issue is specific to the remote broker. You can use the following Docker command to start:

```shell
docker run -d --name emqx -p 1883:1883 -p 8083:8083 emqx/emqx
```

Thank you again for your patience, and I hope these suggestions will help resolve your issue.

**Comment by Thinhle2701** [comment]
It has solved already! Thank you for your help
