### ISSUE TITLE
It keeps reconnecting when you enter a wrong message

### ISSUE THREAD

**Issue by GoodCooking** [emqx/MQTTX#1532]
Version：v1.9.7
If you enter the wrong information, you will continue to reconnect after connecting. If you delete the wrong connection, you will still be reminded that you are reconnecting. You need to close the program and open it again to solve the problem.

**Comment by ysfscream** [comment]
Hello, @GoodCooking 

Regarding the reconnection issue you mentioned, this usually happens because most reconnection attempts are set in the settings. The software attempts to reconnect up to this limit when an error is encountered. You can adjust this limit in the settings. Additionally, reconnection will forcibly stop if you enter an editing page or leave the current page. Another solution is forcing refresh (e.g., CMD+R on Mac or Ctrl+R on Windows).

<img width="1137" alt="image" src="https://github.com/emqx/MQTTX/assets/21299158/b006308b-5176-49d2-b657-6265e57fc6dd">

<img width="1137" alt="image" src="https://github.com/emqx/MQTTX/assets/21299158/eb815ebd-fc90-411b-9efb-f436e5bc7f31">

Furthermore, if the software attempts to reconnect, you can click the cancel button to stop the process. However, if the connection speed is broken, clicking the button in time might be challenging. We consider adding a specific "Force Stop Reconnection" button in future software versions. This feature would provide a more direct and convenient way for users to control the reconnection process, avoiding unnecessary waiting and difficulties in operation.

I hope this information is helpful to you. Please don't hesitate to contact us for further assistance or suggestions.

Best regards.

**Comment by GoodCooking** [comment]
Hello,

Thank you for your detailed explanation of the reconnection issue.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The information you provided was really helpful, and I tried it again in the program exactly as you said.

I&nbsp; agree that adding a "Force Stop reconnect" button in future software releases will enhance the user experience and provide more control to the user.

Also, I would like to mention that English is not my first language.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Some of the above email responses were generated with the help of AI, so please understand if there was any inaccuracy or unclear expression.

Best wishes.&nbsp;


921268871
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月27日(星期三) 凌晨1:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [emqx/MQTTX] It keeps reconnecting when you enter a wrong message (Issue #1532)





 
Hello, @GoodCooking
 
Regarding the reconnection issue you mentioned, this usually happens because most reconnection attempts are set in the settings. The software attempts to reconnect up to this limit when an error is encountered. You can adjust this limit in the settings. Additionally, reconnection will forcibly stop if you enter an editing page or leave the current page. Another solution is forcing refresh (e.g., CMD+R on Mac or Ctrl+R on Windows).
 image.png (view on web) image.png (view on web) 
Furthermore, if the software attempts to reconnect, you can click the cancel button to stop the process. However, if the connection speed is broken, clicking the button in time might be challenging. We consider adding a specific "Force Stop Reconnection" button in future software versions. This feature would provide a more direct and convenient way for users to control the reconnection process, avoiding unnecessary waiting and difficulties in operation.
 
I hope this information is helpful to you. Please don't hesitate to contact us for further assistance or suggestions.
 
Best regards.

**Comment by ysfscream** [comment]
The new https://github.com/emqx/MQTTX/releases/tag/v1.9.9 fixes the reconnection issue. Leaving a page or re-editing a connection now correctly stops reconnecting.

Thanks for your feedback!
