### ISSUE TITLE
[Feature] Setting to disable copilot

### ISSUE THREAD

**Issue by Djhg2000** [emqx/MQTTX#1534]
#### Motivation

We're running MQTTX inside our organization for debugging our internal MQTT network. We don't want to potentially leak any confidential information to OpenAI through the copilot integration.

#### Detailed design

Basically just a switch in the settings menu to disable any communication with OpenAI/copilot/any online AI assistant.

#### Alternatives

For now I've set an invalid API key but I might as well set a line in `/etc/hosts` to point any OpenAI domain to localhost. I'd rather MQTTX never tried contacting any AI assistant at all though. We could recommend our developers to use another MQTT client but MQTTX is the best one we've tried for debugging so far. Another temporary solution would be to downgrade to MQTTX 1.9.6 but then we'd be stuck not getting any more bugfixes. In theory we could maintain an internal fork with the copilot code ripped out but I don't think maintaining that would be viable long-term as the MQTT team is very small.

#### More detail (optional)

Personally I want a setting to disable any AI assistant whether it be online or offline, but that's probably just me.

**Comment by ysfscream** [comment]
Hello @Djhg2000,

Thanks for using MQTTX! We understand the importance of maintaining the confidentiality of your internal MQTT network and want to make sure you know that we are our top priorities.

To address your concern, MQTTX is designed to communicate with OpenAI or any online AI assistant only if a valid API key is provided. If you do not set an API key in the settings, the application will not attempt to establish any connection with OpenAI's services. This ensures that your data remains within control and is not shared externally.

<img width="846" alt="image" src="https://github.com/emqx/MQTTX/assets/21299158/569b4963-bc99-4ccf-b468-f417798f904f">

However, we recognize the importance of providing explicit controls for our users. Because of your feedback, we plan to introduce a switch in the settings menu to turn off any interaction with Copilot or any online AI assistant altogether. This will provide an additional layer of assurance and allow organizations like yours to use MQTTX without any concerns about data leakage.

We appreciate your suggestion and understand that while the Copilot feature can benefit many users, especially for testing and debugging with public data, it is equally important to respect the needs of users handling sensitive information. The upcoming switch will ensure that you can comfortably continue using MQTTX, which you've found to be the best tool for debugging, without the need to resort to workarounds or maintain an internal fork.

Thank you for your understanding and your continued support. We're committed to making MQTTX the best tool for all our users.

**Comment by ysfscream** [comment]
@Djhg2000 Thanks for your feedback. Now the https://github.com/emqx/MQTTX/releases/tag/v1.9.8 supported
