### ISSUE TITLE
[Bug] After installing V1.9.8, the application opens to a blank screen.

### ISSUE THREAD

**Issue by 1pine** [emqx/MQTTX#1561]
版本：1.9.8
现象：安装后打开，应用为白屏，只有顶部file菜单。
尝试：尝试删除mqttx.db文件、尝试以管理员身份启动，均无作用

**Comment by ysfscream** [comment]
Thank you for reporting this issue. To better understand and resolve this issue, please let us know which version of MQTTX you were using before upgrading to 1.9.8? Knowing the previous version could help us pinpoint any changes or updates causing this problem.

**Comment by ysfscream** [comment]
As a part of our troubleshooting process, we would like to check if the issue might be related to a database migration error when upgrading to version 1.9.8. Could you please look at your MQTTX database file, specifically the SettingEntity table, and see if there are any newly added fields?

<img width="164" alt="image" src="https://github.com/emqx/MQTTX/assets/21299158/329b1e8a-cb84-41a3-a5ff-248fdf813443">

This information will help us determine if the white screen issue is due to a failure in database migration from an older version to the latest version. Your cooperation is very important and will help us resolve this issue quickly.

**Comment by cqr-github** [comment]
same problem! help! 
![image](https://github.com/emqx/MQTTX/assets/71479495/f1b68848-0f89-4b9e-ade1-e50f2bd40044)
![image](https://github.com/emqx/MQTTX/assets/71479495/81f0debd-8b17-4356-a828-8280149326be)
![image](https://github.com/emqx/MQTTX/assets/71479495/0be3983a-95dd-4371-902f-3a27825ffbad)

**Comment by dlyili** [comment]
我这边也是1.9.8.0，这边出现白屏的可能是因为接收到的json数据比较大，有462k，软件先显示了json字符串，等一会软件就变成白板了，使用菜单[显示]->[重新加载]，会显示主界面，然后又变成白板。

**Comment by ysfscream** [comment]
- Use two ways to handle the white screen situation at https://github.com/emqx/MQTTX/releases/tag/v1.10.0
    - By resetting the database
    - Optimizing the display of large messages in the message list

Thanks for your feedback. If there is any problem, I will reopen this issue.

**Comment by dlyili** [comment]
这个问题仍然没有解决，我是通过打开MQTTX.db),删除MessageEntity表中的最新数据（订阅到的json数据大），然后点击菜单[显示]-->[强制重新加载]，显示正常。
