### ISSUE TITLE
"Usage hint on the message card" issue with AWS IoT Core

### ISSUE THREAD

**Issue by bayoojo1** [emqx/MQTTX#1596]
### Discussed in https://github.com/emqx/MQTTX/discussions/1595

<div type='discussions-op-text'>

<sup>Originally posted by **bayoojo1** March  3, 2024</sup>
I'm using mqttx client to publish data into aws iot core. When I automate my payload with a script, it prepends the text "Used script.js Function And schema.proto Schema" on top of the payload. Getting to the AWS IoT core, the payload does not display, but instead, I get an error: "Message cannot be displayed in specified format."
I can successfully publish the same payload without any error if I don't use a script. So, how can I remove this usage hint?
<img width="283" alt="usagehint" src="https://github.com/emqx/MQTTX/assets/19572379/43b4305e-c384-4b95-9c5c-b9d7e0c58a2e">
<img width="470" alt="awserror" src="https://github.com/emqx/MQTTX/assets/19572379/befbaba3-05b8-4a75-b1c7-23fc4fb62972">
</div>

**Comment by ysfscream** [comment]
The issue you're encountering is due to the `script` and `schema` being applied to your payload before publishing. To understand their effects and how to manage them. Please look at the MQTTX documentation here: https://mqttx.app/docs/advanced#script.

You'll find an option to remove the script at the top of the page. This allows you to customize the data format according to the requirements of your receiving end. I hope this helps.

**Comment by bayoojo1** [comment]
> The issue you're encountering is due to the `script` and `schema` being applied to your payload before publishing. To understand their effects and how to manage them. Please look at the MQTTX documentation here: https://mqttx.app/docs/advanced#script.
> 
> You'll find an option to remove the script at the top of the page. This allows you to customize the data format according to the requirements of your receiving end. I hope this helps.

Thanks @ysfscream but I've checked through the page you suggested and could not find or see anywhere to disable that script usage hint on the message card. There should be an option to disable the hint. It's been rejected by AWS core.
<img width="351" alt="usagehint" src="https://github.com/emqx/MQTTX/assets/19572379/01ccb320-6db1-4e11-8c80-44aca3796ef5">

**Comment by ysfscream** [comment]
Still need to understand this issue; this prompt cannot be deleted. This prompt appears because you have enabled the script and schema to parse your payload.

**Comment by bayoojo1** [comment]
> Still need to understand this issue; this prompt cannot be deleted. This prompt appears because you have enabled the script and schema to parse your payload.

The issue is this:
1. When I use the script, I always get an error on AWS as shown below:
<img width="470" alt="awserror" src="https://github.com/emqx/MQTTX/assets/19572379/284bfc81-1053-4a5d-9696-99d3a7fef465">

2. But when I don't use the script, AWS accept and display the sent data like below
<img width="445" alt="correctMessage" src="https://github.com/emqx/MQTTX/assets/19572379/8912b7bc-d4ca-490c-b0ee-27c853691b33">

So, I think the usage hint is being sent along with the message to AWS, and AWS does not like what is being sent.

**Comment by ysfscream** [comment]
Ah, I get it. The prompt you see is just for your info and doesn't get sent to AWS. It's just there to inform you that a script or schema is processing your message. The issue is your script or schema changes the payload format, which AWS doesn't accept. You must adjust your script/schema to match AWS's expected format.

Understand your script/schema's function and the outgoing format to fix this issue.
