### ISSUE TITLE
[BUG] CONNECT command append unwanted string to ClientID

### ISSUE THREAD

**Issue by cmaruti** [emqx/MQTTX#1714]
#### What happened

The Client ID provieded in the connection parameters was not reflected 1:1 into the CONNECT command. By inspecting the newtork traffic (i.e. Wireshark) it was detected that MQTTX append a random suffix; altering it without any notice/way to control this behavior may cause some headhache.

#### Expected

Some MQTT services expect to receive a precise MQTT client ID as a part of the authentication process, before granting access to the topics queue. 

- Client ID inserted in MQTTX UI: `gabbagabbahey`
- Client ID provided by MQTTX to the remote service: `gabbagabbahey_1720423123000`

#### Environment

- OS: Microsoft Windows [Versione 10.0.22631.3737]
- MQTTX Version: v1.10.0

#### More detail

![image](https://github.com/emqx/MQTTX/assets/2283072/ee0879a3-d683-4beb-83cd-bfacb6c88c20)

![image](https://github.com/emqx/MQTTX/assets/2283072/22de231d-c6f1-4654-9c33-f3736ff7afeb)

**Comment by ysfscream** [comment]
Hi, thanks for using it. It shouldn't be a bug because you have turned on the timestamp auto-add feature. You can click the `clock` icon to turn it off.

<img width="554" alt="image" src="https://github.com/emqx/MQTTX/assets/21299158/4c995298-6ef0-4b7d-840f-28cd05beea66">

This prevents disconnection issues when using the same Client ID to connect in different locations.

**Comment by cmaruti** [comment]
Hi @ysfscream and thank you for your quick rountrip. I was totally unaware of it! 

Have a great day

**Comment by ysfscream** [comment]
If there is no update, I will close this issue. Thanks.
