### ISSUE TITLE
MQTT over TLS: expired certificate

### ISSUE THREAD

**Issue by marcelstoer** [emqx/MQTTX#262]
Connecting to m20.cloudmqtt.com:22703 over TLS the client reports

> Error: certificate has expired

How can I verify that? How can I load the certificate to verify the chain? I would like to see for myself before reporting this to the cloud provider.

![cert-error](https://user-images.githubusercontent.com/624195/86526967-83945980-be9a-11ea-9864-a591d9e1a1f1.jpg)

**Comment by ysfscream** [comment]
@marcelstoer Hello, I am not sure whether you are using your own deployed `Broker`. If yes, you may use the `openssl` command to check if the server certificate has expired.

```shell
openssl x509 -in <YourCertName>.crt -noout -dates
```

And if not, please confirm whether it's `CA signed server` or `self signed`, if it's `self-signed authentication`, you may need to upload your client certificate, etc.

**Comment by marcelstoer** [comment]
I think there is a misunderstanding. Take a look at my URL. I'm using the public service of CloudMQTT. So, not my own broker and no self-signed cert.

In the meantime I found out I can connect to this host just fine over TLS with e.g. the MQTT.fx. This confirms my suspicion that there is actually no problem with the cert on the server end but a bug somewhere in your app. I was looking for  exception stacktraces in the macOS console but didn't see any. Do you write your logs somewhere else?

**Comment by ysfscream** [comment]
Oh, I see. In fact, I have also found that through some tests, the TLS/TLS connection method of `MQTT.fx` and `MQTTX` will be slightly different.

`MQTT.fx` is implemented through `Java`. It seems that some certificate authentication methods are not needed, and `MQTTX` It is implemented through by `JavaScript` and runs in `Node.js`, I use the same `JavaScript` client will also have the same error, because its internal default has strict requirements for certificate authentication, but I made some internal modifications in the next version, may be able to achieve some not so strict requirements Connection.

For the log function has not yet been added, I will continue to implement in later versions, thank you very much! :)

**Comment by ysfscream** [comment]
Hi, this issue may have been resolved in [v1.3.2](https://github.com/emqx/MQTTX/releases/tag/v1.3.2), thank you for your feedback. I will close this issue.

**Comment by marcelstoer** [comment]
Thanks for the new release. However, the app would not start on macOS due to

> Can’t be opened because Apple cannot check it for malicious software

The only remedy seems to resort to the command line.

```
$ cd /Applications
$ xattr -rd com.apple.quarantine MQTTX.app
```

Secure connection to CloudMQTT can now be established. Thanks.

**Comment by ysfscream** [comment]
@marcelstoer You are welcome! Maybe you can download it from the [Mac App Store](https://apps.apple.com/us/app/mqttx/id1514074565) to solve this problem, and v1.3.2 has now been submitted for review, you may need to wait, It will also be convenient for you to update the software later. In the future we will continue to optimize and update, thank you for your use :)
