### ISSUE TITLE
No error message prompt when publish failed

### ISSUE THREAD

**Issue by supermareo** [emqx/MQTTX#342]
**publish to to/client/test in mqttx**
![image](https://user-images.githubusercontent.com/9459926/97947704-0ede1700-1dc9-11eb-9308-e84973fb255d.png)

**Error message in emqx.log**
![image](https://user-images.githubusercontent.com/9459926/97947710-169dbb80-1dc9-11eb-92b8-dcd9882d8858.png)

**Comment by ysfscream** [comment]
Thanks for your feedback. Could you please tell me how to reproduce it? This maybe a bug.

**Comment by supermareo** [comment]
> Thanks for your feedback. Could you please tell me how to reproduce it? This maybe a bug.

modify `emqx.conf`:
```
allow_anonymous = false
acl_nomatch = deny
zone.external.enable_acl = on
```

modify `acl.conf`
```
{allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}.
{allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}.
{deny, all, subscribe, ["$SYS/#", {eq, "#"}]}.
{deny, all}.
```

restart emqx broker and load the `emqx_auth_redis` plugin

add an user named `test` with password `test` in redis:
```
hset mqtt_user:test password test
```

add acl rule in redis:
```
hset mqtt_acl:test test_topic 2
```

then connect to the emqx broker by mqttx and publish to test_topic.

**Comment by ysfscream** [comment]
@supermareo Hi, thanks for your description, I reproduced this problem, but it's not a MQTTX problem.

Because it's in the MQTT protocol that QoS0 has no response, neither v3.1.1 nor v5.0 can receive an error response.

QoS1 and QoS2 don't define the wrong return values in the v3.1.1 protocol, only correct return values, QoS1, QoS2 define wrong return value and return code in v5.0 protocol.

So you can use MQTT v5.0 to verify this problem. Hope it can help you! :)

**Comment by supermareo** [comment]
Thanks for your reply. I change to MQTT v5.0 and QoS1, it's working now. (๑•̀ㅂ•́)و✧
