### ISSUE TITLE
[Feature] Topic browser

### ISSUE THREAD

**Issue by daenney** [emqx/MQTTX#534]
#### Motivation

When connecting to a broker for exploration purposes you don't always know what topics are available. It would be nice if there was a topic browser, that showed all topics on the broker.

#### Detailed design

[MQTT Explorer](http://mqtt-explorer.com/) provides this feature. It seems to do this by subscribing to `#` and then continuously updating a tree view.

This would relate partially to #533.

#### More details

I realise it's not really possible to always show all topics. Even by subscribing to `#` the client would only become aware of topics that have messages published to them but that's already a lot more helpful than nothing at all.

**Comment by oceanlvr** [comment]
@daenney  thanks for your suggestion, it's a great idea that topics show like a tree view when we sub `#` just in `MQTT X`. BTW, we developed another product named `EMQX dashboard` which clearly shows the sub/pub topic in the broker **if your MQTT broker is `EMQX`**.

**Comment by oceanlvr** [comment]
@ysfscream MQTT Explorer sub the `#` and `$SYS/#` automatically:

![image](https://user-images.githubusercontent.com/36698124/111062973-2b146200-84e7-11eb-9e64-f230760dc180.png)

 and show as a tree view like:

![image](https://user-images.githubusercontent.com/36698124/111062969-26e84480-84e7-11eb-9a1c-2e3370ed6891.png)

what's your opinion? :)

**Comment by daenney** [comment]
I had completely forgotten about the dashboard, that’s a great point. It would be nice to have a similar capability even if the broker isn’t emqx.

**Comment by ysfscream** [comment]
@daenney Hi! Thanks for your great suggestions and @oceanlvr thanks for your reply.

In fact, this functional design is there from the beginning, but I don't think it should be a default main feature, perhaps an extended feature is better and optional. We will consider implementing it later, but there is no actual idea. Maybe we can do more and discuss here.

**Comment by distinctdan** [comment]
I'll add that this is pretty much a deal breaker feature for me. Right now, there's no way to organize any of the messages, they just get dumped in one big giant list. I'm subscribing to a stream of events across maybe 20 topics, so I really need a way to organize them. I recognize tree views are hard to build - an easier, although not as good feature would be:
 - Make clicking the topic toggle showing messages from that topic in the main list, so that you could hide message from certain topics, as a way to filter.
 - Include a message count in the topic name instead of QoS. QoS isn't really important to view, and seeing the number of messages for a topic would be more useful.

**Comment by ysfscream** [comment]
Topic Tree is available at https://github.com/emqx/MQTTX/releases/tag/v1.11.0

This feature is currently in the `Beta` version, and there may be some instabilities or inability to meet expectations. However, I think the basic function of viewing can be achieved.

Therefore, I will close this issue. We can discuss suggestions or bug reports for topic tree milestone 2 in the issue if there is new feedback or discussion. Thank you all.
