### ISSUE TITLE
Areas that can be optimized in operation

### ISSUE THREAD

**Issue by bambuo** [emqx/MQTTX#571]
The platform I use: 
Operating system: Deepin 20.2.1. 
Software version: MQTTX-1.5.4.AppImage. 
Found the following problems with the user experience: 
1.  The topic subscription created cannot be modified again. 
2.  All topics are lost after closing the connection, which is very inconvenient in the case of multiple themes. 
3.  Although the program is developed using front-end technology, it also wants to hide which menu bars at the top. 
I hope the tools are getting better and better.

**Comment by ysfscream** [comment]
Hi! Thanks for using it and your great suggestions!

> The topic subscription created cannot be modified again.

OK, this will be included in the future version.

> All topics are lost after closing the connection, which is very inconvenient in the case of multiple themes.

YES! This is based on the `clean session` configuration. When the value is `true`, all topics will be removed, because it is invalid. Only when the value is `false` will be persistent storage, so the next version will be persistent storage and add the automatic recovery subscription function.

> Although the program is developed using front-end technology, it also wants to hide which menu bars at the top.

Sorry, I don’t understand the meaning of a `hidden menu bar`?

> I hope the tools are getting better and better.

Thanks again!

**Comment by bambuo** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月17日(星期一) 下午2:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [emqx/MQTTX] Areas that can be optimized in operation (#571)






嗨！谢谢你使用它和你的伟大建议！

无法再次修改创建的主题订阅。

好的，这会在以后的版本中包括。

关闭连接后所有主题都会丢失，在多主题的情况下非常不方便。

是的，这是基于清洁会话配置。当值为真实的时，所有主题都将被删除，因为它是无效的。假会持久化存储，所以下个版本会持久存储并增加自动恢复订阅功能。

虽然该程序是使用前端技术开发的，但它也想隐藏哪些菜单栏在顶部。

不好意思，我不懂a的意思隐藏菜单栏?

希望工具越来越好。

再次感谢！

—
您正在接收此消息，因为您编写了线程。
直接回复此邮件，在GitHub上查看或者取消订阅.

**Comment by ysfscream** [comment]
Currently, most of it has already been implemented, and I will close this issue. Thanks.
