### ISSUE TITLE
[Help] I don't think the guide of develop in Readme works on M1 Mac

### ISSUE THREAD

**Issue by apprentice1988** [emqx/MQTTX#579]
#### 

I failed to build mqttx code on my M1 Mac. Some packages' installations failed such as electron and others.

#### More detail (optional)

My Mac system is below:
![image](https://user-images.githubusercontent.com/3086940/119230080-45a13200-bb4d-11eb-83dd-302c82233b65.png)

The error snapshot is below:
![image](https://user-images.githubusercontent.com/3086940/119230111-66698780-bb4d-11eb-9b3a-883ae3faf5f6.png)

**Comment by ysfscream** [comment]
Hello, thanks for your feedback!

Because I don’t have a MacBook with an M1 chip, I can't reproduce this issue.

But as far as I know, the application should be able to run normally on the computer with the M1 chip? The inability to compile and run may be caused by the version of Electron, which needs to be upgraded to v11.x.x or higher.
