### ISSUE TITLE
On the issue of the message content not being formatted after selecting JSON format for display

### ISSUE THREAD

**Issue by BarryYBL** [emqx/MQTTX#598]
The encoding received by subscription cannot be displayed in JSON format. If I paste the JSON format of the published message, I should take the initiative to help me format the JSON format after pasting it. However, now there is no help for me to format the JSON format, so I must re-select the JSON format every time. I think that's what a lot of developers want！
Thank you！

![image](https://user-images.githubusercontent.com/46100874/121538778-a084c580-ca37-11eb-8252-ccfec825e613.png)

**Comment by ysfscream** [comment]
@BarryYBL Hello! Thanks for your feedback! YES, you are right, currently it does not automatically help you format JSON data, if you need to format, you need to paste in Plaintext mode, and then select to JSON format, in order to automatically help you format. JSON format is currently the most useful, can only help you check whether the format is correct, later we can optimize the automatic formatting of the problem.

**Comment by BarryYBL** [comment]
Thank you very much

**Comment by ysfscream** [comment]
Hi, thanks again! Currently supports automatic beautification of received JSON format data.

![image](https://user-images.githubusercontent.com/21299158/124690701-2a2b9400-df0d-11eb-969f-9b83ce2c6021.png)

And you can right-click to use the context menu to beautify JSON data.

![image](https://user-images.githubusercontent.com/21299158/124690815-521af780-df0d-11eb-8c3d-fed11741956d.png)

**Comment by BarryYBL** [comment]
OK，veryGood！
