### ISSUE TITLE
[Bug] websocket DisConnect Can't turn off

### ISSUE THREAD

**Issue by ChunMengLu** [emqx/MQTTX#671]
#### What did I do

There is a high probability that websocket DisConnect has a problem. It cannot be turned off and can only be restarted.

![x](https://user-images.githubusercontent.com/2115440/131107650-18b74448-c356-4b69-a3e4-499d6d62dfc1.gif)

#### What happened

but use http://tools.emqx.io is ok!!!

#### Expected

What is the expected result.

#### Environment

- OS: windows 10
- MQTTX：v1.6.0

#### More detail

More detail include `log` information or screenshot

**Comment by ysfscream** [comment]
Hey! @ChunMengLu Thanks for using and feedback! I also found this problem just the other day, I don't know if it's a network problem or a configuration problem with your MQTT broker. Because this problem occurs when MQTTX does not receive DISCONNECT messages because the MQTT broker does not send them, maybe I can add a timeout determination for the DISCONNECT.

**Comment by ChunMengLu** [comment]
The new version has been resolved。
