### ISSUE TITLE
subscribed topics disappear

### ISSUE THREAD

**Issue by programmer131** [emqx/MQTTX#724]
after updating to v1.6.1, I added topic for subscription, but while adding another broker url, all subscribed topics disappeared for first broker, restarted mqtt, nothing happen, so now I need to add list of topics again.

#### Environment

- OS: win10
- MQTTX version v1.6.1

**Comment by oceanlvr** [comment]
@ysfscream I have reproduced this issue, I am sure it was caused by an unsafe subscription operation without `id` filed in the model layer. So it may be related to issue #725 

@programmer131  Could you please try this remote branch version?

oceanlvr:sub/fix: https://github.com/oceanlvr/MQTTX/tree/sub/fix

Tell us if you can still reproduce nor not! ( if possible :) 
Waiting for your reply!

**Comment by almirus** [comment]
same bug

**Comment by oceanlvr** [comment]
@almirus @programmer131 Have you try the latest version `v1.6.2`, let me know if it fixes this issue.

**Comment by almirus** [comment]
@oceanlvr after 1.6.1 all saved servers (with topics) was deleted
after 1.6.2 - nothing recovered

**Comment by almirus** [comment]
i have already "restored" through creation anew connection 😎

**Comment by oceanlvr** [comment]
So what's about problem？
Fix or not
@almirus

**Comment by oceanlvr** [comment]
@almirus Upgrading to a new version won't get the lost connection configuration back, but there won't be a connection loss in the new version, please upgrade to the latest version v1.6.2 and test the subscription again to see if this patch fixes your problem.
