### ISSUE TITLE
[Help] m1 pro open mqtt x no window

### ISSUE THREAD

**Issue by ishells** [emqx/MQTTX#791]
#### I am using a macbook 14 computer with m1 pro to install mqtt x and open without a graphical interface

Computer：2021 macbook pro m1 pro 14
Release：MQTTX-1.6.2-universal.dmg

#### Some things like this:
![image](https://user-images.githubusercontent.com/47415693/143367017-d94ebaf5-89e2-4216-8be1-637593dcbb45.png)

**Comment by oceanlvr** [comment]
@ishells The reason is that there is currently no binary packaging for the M1 version of node-sqlite, and we'll look at the node-sqlite repository and follow up if it's updated. The solution is to use MQTT X prior to version 1.6.0, which is based on lowdb and does not have compatibility issues.

https://github.com/emqx/MQTTX/issues/787, https://github.com/emqx/MQTTX/issues/690

**Comment by ishells** [comment]
@oceanlvr Thanks for your reply. Got it and i will give it a try
