### ISSUE TITLE
[Help] I can't create two connections with the same Client ID and different connection addresses.

### ISSUE THREAD

**Issue by linG5821** [emqx/MQTTX#799]
#### Describe the problem you Confuse

I can't create two connections with the same Client ID and different connection addresses.

#### More detail (optional)
I created a connection to use the `client1` to be client ID, the connection address is my local, then I want to add another connection, but also use `client1` , but the connection address uses a new address, click the connection button, no Tips and reactions, but when I change to `client2`, it works.

**Comment by ysfscream** [comment]
Thanks for the feedback! After my testing, I found that it is indeed a bug because the ClientID is unique in the database, maybe we need to optimize a little for this, @oceanlvr please follow up on it.

![image](https://user-images.githubusercontent.com/21299158/144365729-0de11811-cfc0-4784-88c0-958a81687c25.png)

**Comment by ysfscream** [comment]
It's fixed on https://github.com/emqx/MQTTX/releases/tag/v1.7.1
