### ISSUE TITLE
[Feature] Mqttx topic displays problems that cannot be seen clearly

### ISSUE THREAD

**Issue by starplatinum3** [emqx/MQTTX#901]
Mqttx topic displays problems that cannot be seen clearly
Mqttx topic显示看不太清的问题

Some topics in mqttx can't be seen clearly
Mqttx 有些topic 显示的颜色看不太清楚

If  change to light theme, you may not see the bright topic clearly
如果换成light  theme 可能又会造成亮色的topic看不太清楚

Can some bright and dark colors be more obvious by using the way of matching bright front color and dark background colors, but this is a small problem..
能不能一些亮色和暗色比较明显的，使用亮色和暗色搭配的方式，不过这是个小问题。。

Pictures are in the link
https://acc15t4bm5.feishu.cn/docs/doccnOxxRSd3UWEh2obL4yETvrx

**Comment by ysfscream** [comment]
@starplatinum3 OK, thanks for your use. Because in fact, the color is random every time, it does not change according to the system theme, if you feel that it is not very clear to see, you can right-click in the context menu, Edit Topic, manually select a suitable color.

因为其实因为颜色每次都是随机的，它不会根据系统主题而变化，如果您感觉到看不太清，可以右键菜单里，编辑 Topic，手动选择一个适合的颜色

<img width="221" alt="image" src="https://user-images.githubusercontent.com/21299158/155910464-676c78f5-cf08-4abc-82a4-b3bee0ed28a9.png">

<img width="432" alt="image" src="https://user-images.githubusercontent.com/21299158/155910474-24789c73-7ad2-4164-a78a-bfb9d75be00c.png">

**Comment by starplatinum3** [comment]
thank you

**Comment by ysfscream** [comment]
Thanks for your feedback and use. I will close this issue.
